development: &default
  adapter: postgresql
  database: data-engineering_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: data-engineering_test
